### ISSUE TITLE
Translation for add-ons Helium

### ISSUE THREAD

**Issue by SofiaOganova** [cuba-platform/website-content#43]
We need to translate into Chinese, Russian, French and Italian sentence: "Studio 14 is required to extend Helium without any manual actions."

https://github.com/cuba-platform/website-content/commit/3df97d8af940834bb31664d6acb20ae5c0959688

**Comment by BryanYin** [comment]
Chinese: 使用 Studio 14 扩展 Helium 主题可以不需要任何手动修改。

**Comment by lokalova** [comment]
FR: Il est nécessaire d'utiliser Studio 14 pour créer une extension d'Helium sans aucune action manuelle.
RU: Чтобы использовать все возможности темы Helium, требуется версия Studio 14.

**Comment by pfurini** [comment]
IT: E' necessario utilizzare Studio 14 per poter estendere Helium senza alcuna azione manuale.

**Comment by SofiaOganova** [comment]
Thanks!
